// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATei_imAdtI7XBLkQzuRcR2q9d1qSndMs',
    appId: '1:328361606671:web:6f8c69e059b987b3706d7a',
    messagingSenderId: '328361606671',
    projectId: 'messenger-a2486',
    authDomain: 'messenger-a2486.firebaseapp.com',
    storageBucket: 'messenger-a2486.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6A7XjnLGOvp-Nuumi15D9pwY0hEfgSM4',
    appId: '1:328361606671:android:7ff8c64e30548e44706d7a',
    messagingSenderId: '328361606671',
    projectId: 'messenger-a2486',
    storageBucket: 'messenger-a2486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQzZ9yKsMczRgvQZnXMUbJQ400QfjBKhY',
    appId: '1:328361606671:ios:c1ee991589b76493706d7a',
    messagingSenderId: '328361606671',
    projectId: 'messenger-a2486',
    storageBucket: 'messenger-a2486.firebasestorage.app',
    iosBundleId: 'com.learning.messenger',
  );
}
